title: AxelSpace tech standards
description: A searchable database of all AxelSpace tech standards
url: https://oakjelly21.github.io
markdown: kramdown
collections:
  element:
    output: true
    permalink: /element/:path/
permalink: pretty
