title: AxelSpace tech standards
subtitle: "lorem ipsum"
description: A searchable database of all AxelSpace tech standards
share: "HTML Reference: a free guide to all HTML elements and attributes."
url: https://oakjelly21.github.io
markdown: kramdown
collections:
  element:
    output: true
    permalink: /element/:path/
permalink: pretty
exclude: ['node_modules']
plugins:
  - jekyll-diagrams
